<?php

/**
 * Created by PhpStorm.
 * User: stasm
 * Date: 07.12.2017
 * Time: 10:24
 */
class CategoryServiceTest extends \Tests\TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new \App\Services\CategoryService(app(\Schema\Client::class));
    }

    public function test_all()
    {

    }
}