<?php

/**
 * Created by PhpStorm.
 * User: stasm
 * Date: 07.12.2017
 * Time: 10:24
 */
use App\Services\CategoryService;
use Tests\TestCase;

class CategoryServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new CategoryService(app(\Schema\Client::class));
    }

    public function test_all()
    {
        $result = $this->service->all();
        $this->assertInstanceOf(\Schema\Collection::class, $result);

    }
}